name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-public-vault-8c8cf61e.cb768b32.z1.hashicorp.cloud:8200 
          tlsSkipVerify: false
	  namespace: admin
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t    vault-action-exampleapp
